import { StyleSheet } from 'react-native'

export const settingsStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F7F8FA' },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#F7F8FA' },
  header: { backgroundColor: '#0D1B2A', paddingTop: 56, paddingBottom: 16, paddingHorizontal: 16, alignItems: 'center', justifyContent: 'center' },
  backBtn: { padding: 4, width: 50 },
  backText: { color: '#9CA3AF', fontSize: 22 },
  headerTitle: { color: '#fff', fontSize: 16, fontWeight: '600' },
  scroll: { flex: 1 },
  card: { backgroundColor: '#fff', borderRadius: 16, padding: 16, borderWidth: 1, borderColor: '#E5E7EB', gap: 8 },
  cardHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  cardTitle: { fontSize: 15, fontWeight: '600', color: '#0D1B2A' },
  cardSub: { fontSize: 12, color: '#9CA3AF' },
  label: { fontSize: 11, fontWeight: '600', color: '#9CA3AF', letterSpacing: 0.8, marginTop: 4 },
  input: { backgroundColor: '#F7F8FA', borderRadius: 12, borderWidth: 1.5, borderColor: '#E5E7EB', padding: 12, fontSize: 14, color: '#0D1B2A' },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 4 },
  chip: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 20, borderWidth: 1.5, borderColor: '#E5E7EB' },
  chipActive: { backgroundColor: '#0D1B2A', borderColor: '#0D1B2A' },
  chipText: { fontSize: 13, color: '#6B7280' },
  chipTextActive: { color: '#fff', fontWeight: '500' },
  addBtn: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#0E9F8E', justifyContent: 'center', alignItems: 'center' },
  addBtnText: { color: '#fff', fontSize: 22, fontWeight: '300', lineHeight: 28 },
  emptyServizi: { alignItems: 'center', paddingVertical: 24, gap: 6 },
  emptyServiziIcon: { fontSize: 32 },
  emptyServiziText: { fontSize: 14, color: '#6B7280', fontWeight: '500' },
  emptyServiziSub: { fontSize: 12, color: '#9CA3AF' },
  servizioRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', paddingVertical: 10, borderTopWidth: 1, borderTopColor: '#F3F4F6' },
  servizioLeft: { flex: 1, gap: 2 },
  servizioNome: { fontSize: 14, fontWeight: '600', color: '#0D1B2A' },
  servizioDesc: { fontSize: 12, color: '#9CA3AF', lineHeight: 16 },
  servizioRight: { alignItems: 'flex-end', gap: 4 },
  servizioCosto: { fontSize: 13, fontWeight: '600', color: '#0E9F8E' },
  servizioActions: { flexDirection: 'row', gap: 8 },
  servizioActionBtn: { padding: 4 },
  servizioActionText: { fontSize: 16 },
  saveBtn: { backgroundColor: '#0D1B2A', borderRadius: 14, padding: 16, alignItems: 'center' as const },
  saveBtnDisabled: { opacity: 0.5 },
  saveBtnText: { color: '#fff', fontSize: 15, fontWeight: '600' },
  logoPreview: { width: '100%', height: 80, backgroundColor: '#F7F8FA', borderRadius: 10 },
  logoPlaceholder: { width: '100%', height: 80, backgroundColor: '#F7F8FA', borderRadius: 10, justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: '#E5E7EB', borderStyle: 'dashed' as const },
  logoPlaceholderText: { fontSize: 13, color: '#9CA3AF' },
  logoBtn: { backgroundColor: '#0D1B2A', borderRadius: 12, padding: 12, alignItems: 'center' as const },
  logoBtnText: { color: '#fff', fontSize: 14, fontWeight: '600' as const },
  modalContainer: { flex: 1, backgroundColor: '#F7F8FA' },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 20, paddingTop: 56, backgroundColor: '#0D1B2A' },
  modalTitle: { color: '#fff', fontSize: 16, fontWeight: '600' },
  modalClose: { color: '#9CA3AF', fontSize: 20, width: 40 },
  modalSave: { color: '#0E9F8E', fontSize: 15, fontWeight: '600' as const, width: 40, textAlign: 'right' as const },
  fieldGroup: { gap: 6 },
  fieldLabel: { fontSize: 11, fontWeight: '600', color: '#9CA3AF', letterSpacing: 0.8 },
  fieldInput: { backgroundColor: '#fff', borderRadius: 12, borderWidth: 1.5, borderColor: '#E5E7EB', padding: 12, fontSize: 14, color: '#0D1B2A' },
  costoRow: { flexDirection: 'row', gap: 12 },
  unitaChips: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 4 },
  unitaChip: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 16, borderWidth: 1, borderColor: '#E5E7EB', backgroundColor: '#F7F8FA' },
  unitaChipActive: { backgroundColor: '#0D1B2A', borderColor: '#0D1B2A' },
  unitaChipText: { fontSize: 11, color: '#6B7280' },
  unitaChipTextActive: { color: '#fff', fontWeight: '500' },
  previewBox: { backgroundColor: '#F0FDF4', borderRadius: 12, padding: 14, borderWidth: 1, borderColor: '#0E9F8E', gap: 4 },
  previewLabel: { fontSize: 10, fontWeight: '600', color: '#0E9F8E', letterSpacing: 0.8 },
  previewNome: { fontSize: 15, fontWeight: '600', color: '#0D1B2A' },
  previewDesc: { fontSize: 12, color: '#6B7280' },
  previewCosto: { fontSize: 14, fontWeight: '700', color: '#0E9F8E', marginTop: 4 },
  fiscaleBtn: { backgroundColor: '#fff', borderRadius: 14, padding: 16, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderWidth: 1, borderColor: '#E5E7EB' },
  coloriGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 4 },
  coloreChip: { width: 40, height: 40, borderRadius: 8, justifyContent: 'center', alignItems: 'center' },
  coloreChipActive: { borderWidth: 3, borderColor: '#fff', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.3, shadowRadius: 3, elevation: 4 },
  coloreChipCheck: { color: '#fff', fontSize: 16, fontWeight: '700' as const },
  coloreCustomRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  colorePreviewBox: { width: 28, height: 28, borderRadius: 6 },
  firmaPreview: { fontSize: 22, color: '#374151', fontStyle: 'italic' as const, paddingVertical: 8, textAlign: 'center' as const },
  fiscaleBtnText: { fontSize: 14, color: '#0D1B2A', fontWeight: '500' },
  fiscaleBtnArrow: { fontSize: 18, color: '#9CA3AF' },
  segnalazioneBtn: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#fff', borderRadius: 14, padding: 16, borderWidth: 1, borderColor: '#E5E7EB', gap: 12 },
  segnalazioneBtnIcon: { fontSize: 22 },
  segnalazioneBtnText: { fontSize: 14, fontWeight: '600', color: '#0D1B2A' },
  segnalazioneBtnSub: { fontSize: 12, color: '#9CA3AF', marginTop: 2 },
  infoBox: { backgroundColor: '#EFF6FF', borderRadius: 12, padding: 14, borderWidth: 1, borderColor: '#BFDBFE' },
  infoBoxText: { fontSize: 12, color: '#1D4ED8', lineHeight: 18 },
  infoBoxTextMd: { fontSize: 13, color: '#1D4ED8', lineHeight: 18 },
  listinoTabRow: { flexDirection: 'row', backgroundColor: '#F7F8FA', borderRadius: 12, padding: 4, borderWidth: 1, borderColor: '#E5E7EB' },
  listinoTabBtn: { flex: 1, paddingVertical: 8, borderRadius: 10, alignItems: 'center' as const },
  listinoTabBtnActive: { backgroundColor: '#0D1B2A' },
  listinoTabText: { fontSize: 12, fontWeight: '500', color: '#9CA3AF' },
  listinoTabTextActive: { color: '#fff' },
  fotoUploadArea: { backgroundColor: '#F7F8FA', borderRadius: 12, borderWidth: 1.5, borderColor: '#E5E7EB', borderStyle: 'dashed', padding: 32, alignItems: 'center', gap: 8 },
  fotoCameraArea: { backgroundColor: '#F7F8FA', borderRadius: 12, borderWidth: 1.5, borderColor: '#E5E7EB', padding: 16, alignItems: 'center', gap: 6 },
  fotoUploadIcon: { fontSize: 36 },
  fotoUploadTitle: { fontSize: 14, fontWeight: '600', color: '#0D1B2A' },
  fotoUploadSub: { fontSize: 12, color: '#9CA3AF' },
  vocaleHint: { fontSize: 13, color: '#6B7280', lineHeight: 18, textAlign: 'center' },
  vocaleBtn: { width: 100, height: 100, borderRadius: 50, justifyContent: 'center', alignItems: 'center', marginVertical: 8 },
  vocaleBtnIcon: { fontSize: 36 },
  vocaleStatus: { fontSize: 13, fontWeight: '500' },
  modalCancelLink: { alignItems: 'center', padding: 8 },
  modalCancelText: { fontSize: 13, color: '#9CA3AF' },
})
