import { StyleSheet } from 'react-native'

export const listinoStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F7F8FA' },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  header: { backgroundColor: '#0D1B2A', paddingTop: 56, paddingBottom: 16, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  backBtn: { padding: 4, width: 50 },
  backText: { color: '#9CA3AF', fontSize: 22 },
  headerTitle: { color: '#fff', fontSize: 16, fontWeight: '600' },
  headerAiBtn: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#F0FDF4', borderWidth: 1.5, borderColor: '#0E9F8E', justifyContent: 'center', alignItems: 'center' },
  headerAddBtn: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#0E9F8E', justifyContent: 'center', alignItems: 'center' },
  headerAddBtnText: { color: '#fff', fontSize: 22, fontWeight: '300', lineHeight: 28 },
  empty: { alignItems: 'center', paddingTop: 60, gap: 8 },
  emptyIcon: { fontSize: 36, marginBottom: 8 },
  emptyTitle: { fontSize: 16, fontWeight: '600', color: '#0D1B2A' },
  emptySub: { fontSize: 13, color: '#9CA3AF', textAlign: 'center' },
  emptyBtn: { backgroundColor: '#0E9F8E', borderRadius: 12, paddingHorizontal: 20, paddingVertical: 12, marginTop: 8 },
  emptyBtnText: { color: '#fff', fontSize: 14, fontWeight: '600' },
  servizioCard: { backgroundColor: '#fff', borderRadius: 14, padding: 14, borderWidth: 1, borderColor: '#E5E7EB', flexDirection: 'row', alignItems: 'center', gap: 12, shadowColor: '#0D1B2A', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.04, shadowRadius: 4, elevation: 1 },
  servizioCardSelected: { borderColor: '#0E9F8E', backgroundColor: '#F0FDF4' },
  servizioNome: { fontSize: 14, fontWeight: '600', color: '#0D1B2A' },
  servizioDesc: { fontSize: 12, color: '#9CA3AF', marginTop: 2 },
  servizioCosto: { fontSize: 13, fontWeight: '600', color: '#0B7A6D', marginTop: 4 },
  actionBtn: { padding: 6 },
  saveBtn: { backgroundColor: '#0D1B2A', borderRadius: 14, padding: 16, alignItems: 'center' as const, shadowColor: '#0D1B2A', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.18, shadowRadius: 6, elevation: 2 },
  saveBtnDisabled: { opacity: 0.5 },
  saveBtnText: { color: '#fff', fontSize: 15, fontWeight: '600' },
  modalContainer: { flex: 1, backgroundColor: '#F7F8FA' },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 20, paddingTop: 56, backgroundColor: '#0D1B2A' },
  modalTitle: { color: '#fff', fontSize: 16, fontWeight: '600' },
  modalClose: { color: '#9CA3AF', fontSize: 20, width: 40 },
  modalSave: { color: '#0E9F8E', fontSize: 15, fontWeight: '600' as const, width: 40, textAlign: 'right' as const },
  fieldLabel: { fontSize: 11, fontWeight: '600', color: '#9CA3AF', letterSpacing: 0.8 },
  fieldInput: { backgroundColor: '#fff', borderRadius: 12, borderWidth: 1.5, borderColor: '#E5E7EB', padding: 12, fontSize: 14, color: '#0D1B2A' },
  fieldGroup: { gap: 6 },
  unitaChip: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 16, borderWidth: 1, borderColor: '#E5E7EB', backgroundColor: '#F7F8FA' },
  unitaChipActive: { backgroundColor: '#0D1B2A', borderColor: '#0D1B2A' },
  unitaChipText: { fontSize: 11, color: '#6B7280' },
  unitaChipTextActive: { color: '#fff', fontWeight: '500' },
  previewBox: { backgroundColor: '#F0FDF4', borderRadius: 12, padding: 14, borderWidth: 1, borderColor: '#0E9F8E', gap: 4 },
  previewLabel: { fontSize: 10, fontWeight: '600', color: '#0B7A6D', letterSpacing: 0.8 },
  previewNome: { fontSize: 15, fontWeight: '600', color: '#0D1B2A' },
  previewDesc: { fontSize: 12, color: '#6B7280' },
  previewCosto: { fontSize: 14, fontWeight: '700', color: '#0B7A6D', marginTop: 4 },
  selectionBar: { position: 'absolute', left: 12, right: 12, bottom: 12, backgroundColor: '#0D1B2A', borderRadius: 16, padding: 12, gap: 10 },
  selectionTopRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  selectionCount: { color: '#fff', fontSize: 14, fontWeight: '600' },
  selectionCancel: { color: '#9EC5C0', fontSize: 13, fontWeight: '600' },
  selectionActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  selectionActionBtn: { backgroundColor: 'rgba(255,255,255,0.08)', borderRadius: 10, paddingHorizontal: 10, paddingVertical: 9 },
  selectionActionText: { color: '#fff', fontSize: 12, fontWeight: '600' },
  infoBox: { backgroundColor: '#EFF6FF', borderRadius: 12, padding: 14, borderWidth: 1, borderColor: '#BFDBFE' },
  infoBoxText: { fontSize: 13, color: '#1D4ED8', lineHeight: 18 },
  listinoTabRow: { flexDirection: 'row', backgroundColor: '#F7F8FA', borderRadius: 12, padding: 4, borderWidth: 1, borderColor: '#E5E7EB' },
  listinoTabBtn: { flex: 1, paddingVertical: 8, borderRadius: 10, alignItems: 'center' as const },
  listinoTabBtnActive: { backgroundColor: '#0D1B2A' },
  listinoTabText: { fontSize: 12, fontWeight: '500', color: '#9CA3AF' },
  listinoTabTextActive: { color: '#fff' },
  fotoUploadArea: { backgroundColor: '#F7F8FA', borderRadius: 12, borderWidth: 1.5, borderColor: '#E5E7EB', borderStyle: 'dashed', padding: 32, alignItems: 'center', gap: 8 },
  fotoCameraArea: { backgroundColor: '#F7F8FA', borderRadius: 12, borderWidth: 1.5, borderColor: '#E5E7EB', padding: 16, alignItems: 'center', gap: 6 },
  fotoUploadIcon: { fontSize: 36 },
  fotoUploadTitle: { fontSize: 14, fontWeight: '600', color: '#0D1B2A' },
  fotoUploadSub: { fontSize: 12, color: '#9CA3AF' },
  fotoHint: { fontSize: 13, color: '#6B7280', lineHeight: 18 },
  vocaleHint: { fontSize: 13, color: '#6B7280', lineHeight: 18, textAlign: 'center' },
  vocaleBtn: { width: 100, height: 100, borderRadius: 50, justifyContent: 'center', alignItems: 'center', marginVertical: 8 },
  vocaleBtnIcon: { fontSize: 36 },
  vocaleStatus: { fontSize: 13, fontWeight: '500' },
  modalCancelLink: { alignItems: 'center', padding: 8 },
  modalCancelText: { fontSize: 13, color: '#9CA3AF' },
})
