import { StyleSheet } from 'react-native'
import { PROFILO_COLORS as C } from '../../features/profilo/constants'

export const profiloStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: C.gray },
  header: { backgroundColor: C.navy, paddingTop: 56, paddingBottom: 16, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  backBtn: { padding: 4, width: 50 },
  backText: { color: '#9CA3AF', fontSize: 22 },
  headerTitle: { color: '#fff', fontSize: 16, fontWeight: '600' },
  profileCard: { backgroundColor: '#fff', borderRadius: 16, padding: 16, borderWidth: 1, borderColor: C.border, flexDirection: 'row', alignItems: 'center', gap: 14 },
  avatar: { width: 56, height: 56, borderRadius: 28, backgroundColor: C.navy, justifyContent: 'center', alignItems: 'center' },
  avatarText: { color: '#fff', fontSize: 24, fontWeight: '700' },
  profileName: { fontSize: 17, fontWeight: '700', color: C.text },
  profileEmail: { fontSize: 13, color: C.muted, marginTop: 2 },
  card: { backgroundColor: '#fff', borderRadius: 16, padding: 16, borderWidth: 1, borderColor: C.border, gap: 8 },
  cardTitle: { fontSize: 15, fontWeight: '600', color: C.text },
  cardSub: { fontSize: 12, color: C.muted },
  settingRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 4 },
  settingLabel: { fontSize: 14, color: C.text, fontWeight: '500' },
  settingDesc: { fontSize: 12, color: C.muted, marginTop: 1 },
  settingBtn: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 10, borderTopWidth: 1, borderTopColor: C.border },
  settingBtnText: { fontSize: 14, color: C.text },
  settingBtnArrow: { fontSize: 18, color: C.muted },
  logoutBtn: { backgroundColor: '#FEE2E2', borderRadius: 14, padding: 16, alignItems: 'center' as const },
  logoutText: { color: '#EF4444', fontSize: 15, fontWeight: '600' },
  deleteAccountBtn: { backgroundColor: '#DC2626', borderRadius: 14, padding: 16, alignItems: 'center' as const },
  deleteAccountBtnDisabled: { opacity: 0.6 },
  deleteAccountText: { color: '#fff', fontSize: 15, fontWeight: '700' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(13, 27, 42, 0.45)', alignItems: 'center', justifyContent: 'center', padding: 24 },
  passwordModal: { width: '100%', backgroundColor: '#fff', borderRadius: 18, padding: 20, borderWidth: 1, borderColor: C.border },
  passwordModalTitle: { fontSize: 17, fontWeight: '700', color: C.text },
  passwordModalDesc: { fontSize: 13, color: C.muted, lineHeight: 19, marginTop: 6, marginBottom: 16 },
  passwordModalInput: { backgroundColor: C.gray, borderRadius: 12, borderWidth: 1.5, borderColor: C.border, padding: 12, fontSize: 14, color: C.text },
  passwordModalActions: { flexDirection: 'row', gap: 10, marginTop: 16 },
  passwordCancelBtn: { flex: 1, borderRadius: 12, padding: 13, alignItems: 'center' as const, backgroundColor: C.gray, borderWidth: 1, borderColor: C.border },
  passwordCancelText: { color: C.text, fontSize: 14, fontWeight: '600' },
  passwordConfirmBtn: { flex: 1, borderRadius: 12, padding: 13, alignItems: 'center' as const, backgroundColor: '#DC2626' },
  passwordConfirmText: { color: '#fff', fontSize: 14, fontWeight: '700' },
  passwordFieldLabel: { fontSize: 11, fontWeight: '600' as const, color: C.muted, letterSpacing: 0.8, marginBottom: 6 },
  passwordSaveBtn: { flex: 1, borderRadius: 12, padding: 13, alignItems: 'center' as const, backgroundColor: C.navy },
  passwordSaveText: { color: '#fff', fontSize: 14, fontWeight: '700' },
})
