import { Platform, StyleSheet } from 'react-native'

export const nuovoStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F7F8FA' },
  header: { backgroundColor: '#0D1B2A', paddingTop: 56, paddingBottom: 16, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  backBtn: { padding: 4, width: 50 },
  backText: { color: '#9CA3AF', fontSize: 22 },
  headerTitle: { color: '#fff', fontSize: 16, fontWeight: '600' },
  nuovoText: { color: '#0E9F8E', fontSize: 14, width: 50, textAlign: 'right' as const },
  scroll: { flex: 1 },
  chatContent: { padding: 16, gap: 12, flexGrow: 1 },
  emptyChat: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingTop: 80 },
  emptyChatIcon: { fontSize: 40, marginBottom: 12 },
  emptyChatTitle: { fontSize: 16, fontWeight: '600', color: '#0D1B2A', textAlign: 'center' },
  emptyChatSub: { fontSize: 13, color: '#9CA3AF', textAlign: 'center', marginTop: 6, paddingHorizontal: 32 },
  bubble: { maxWidth: '88%', borderRadius: 16, padding: 12 },
  bubbleUser: { alignSelf: 'flex-start', backgroundColor: '#EBF3FF', borderBottomLeftRadius: 4 },
  bubbleAI: { alignSelf: 'flex-end', backgroundColor: '#fff', borderWidth: 1, borderColor: '#E5E7EB', borderBottomRightRadius: 4, shadowColor: '#0D1B2A', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.04, shadowRadius: 3, elevation: 1 },
  bubbleWho: { fontSize: 10, fontWeight: '600', color: '#9CA3AF', marginBottom: 4, textTransform: 'uppercase', letterSpacing: 0.5 },
  bubbleText: { fontSize: 14, lineHeight: 20 },
  bubbleTextUser: { color: '#1E40AF' },
  bubbleTextAI: { color: '#0D1B2A' },
  inputArea: { flexDirection: 'row', gap: 10, padding: 12, backgroundColor: '#fff', borderTopWidth: 1, borderTopColor: '#E5E7EB', alignItems: 'flex-end' },
  input: { flex: 1, backgroundColor: '#F7F8FA', borderRadius: 14, borderWidth: 1.5, borderColor: '#E5E7EB', padding: 12, fontSize: 14, color: '#0D1B2A', maxHeight: 120 },
  sendBtn: { width: 44, height: 44, backgroundColor: '#0E9F8E', borderRadius: 12, justifyContent: 'center', alignItems: 'center', shadowColor: '#0E9F8E', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.3, shadowRadius: 5, elevation: 3 },
  sendBtnDisabled: { opacity: 0.4 },
  sendBtnText: { color: '#fff', fontSize: 20, fontWeight: '600' },
  sceltaContainer: { flex: 1, padding: 20, gap: 14 },
  sceltaTitolo: { fontSize: 24, fontWeight: '700', color: '#0D1B2A', marginTop: 8 },
  sceltaSub: { fontSize: 14, color: '#9CA3AF', marginBottom: 8 },
  sceltaCard: { backgroundColor: '#fff', borderRadius: 16, padding: 18, flexDirection: 'row', alignItems: 'center', gap: 14, borderWidth: 1, borderColor: '#E5E7EB', shadowColor: '#0D1B2A', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.04, shadowRadius: 4, elevation: 1 },
  sceltaCardIconWrap: { width: 36, alignItems: 'center', justifyContent: 'center' },
  sceltaCardBody: { flex: 1, gap: 3 },
  sceltaCardTitle: { fontSize: 16, fontWeight: '600', color: '#0D1B2A' },
  sceltaCardSub: { fontSize: 12, color: '#9CA3AF', lineHeight: 17 },
  clienteBadge: { backgroundColor: '#EBF3FF', borderRadius: 10, padding: 10, borderWidth: 1, borderColor: '#BFDBFE' },
  clienteBadgeText: { fontSize: 13, color: '#1E40AF' },
  prevCard: { backgroundColor: '#fff', borderRadius: 20, borderWidth: 1.5, borderColor: '#0E9F8E', overflow: 'hidden', marginBottom: 12, shadowColor: '#0D1B2A', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.06, shadowRadius: 8, elevation: 2 },
  prevHeader: { backgroundColor: '#0D1B2A', padding: 16 },
  prevHeaderTitle: { color: '#fff', fontSize: 15, fontWeight: '600' },
  prevHeaderSub: { color: '#6B7280', fontSize: 12, marginTop: 2 },
  prevBody: { padding: 16 },
  prevText: { fontSize: 13, lineHeight: 22, color: '#374151', fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace' },
  saveBtn: { backgroundColor: '#0E9F8E', borderRadius: 14, padding: 14, alignItems: 'center' as const, marginBottom: 8, shadowColor: '#0E9F8E', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.25, shadowRadius: 6, elevation: 2 },
  saveBtnDone: { backgroundColor: '#D1FAE5' },
  saveBtnText: { color: '#fff', fontSize: 15, fontWeight: '600' },
  pdfBtn: { backgroundColor: '#0D1B2A', borderRadius: 14, padding: 14, alignItems: 'center' as const, marginTop: 4, shadowColor: '#0D1B2A', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.18, shadowRadius: 6, elevation: 2 },
  pdfBtnText: { color: '#fff', fontSize: 15, fontWeight: '600' },
  recapCard: { backgroundColor: '#fff', borderRadius: 16, borderWidth: 1.5, borderColor: '#0E9F8E', overflow: 'hidden', marginBottom: 16, shadowColor: '#0D1B2A', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.06, shadowRadius: 8, elevation: 2 },
  recapHeader: { backgroundColor: '#F0FDF4', padding: 14, borderBottomWidth: 1, borderBottomColor: '#D1FAE5' },
  recapHeaderTitle: { fontSize: 15, fontWeight: '600', color: '#065F46' },
  recapHeaderSub: { fontSize: 12, color: '#0B7A6D', marginTop: 2 },
  recapText: { fontSize: 13, color: '#374151', lineHeight: 20, padding: 14, fontFamily: 'monospace' },
  recapActions: { flexDirection: 'row', gap: 10, padding: 14, paddingTop: 0 },
  recapConfirmBtn: { flex: 1, backgroundColor: '#0D1B2A', borderRadius: 12, padding: 12, alignItems: 'center' as const, shadowColor: '#0D1B2A', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.15, shadowRadius: 5, elevation: 2 },
  recapConfirmText: { color: '#fff', fontSize: 14, fontWeight: '600' as const },
  recapEditBtn: { flex: 1, backgroundColor: '#F7F8FA', borderRadius: 12, padding: 12, alignItems: 'center' as const, borderWidth: 1, borderColor: '#E5E7EB' },
  recapEditText: { color: '#374151', fontSize: 14, fontWeight: '500' as const },
  paymentCard: { backgroundColor: '#F7F8FA', borderRadius: 12, borderWidth: 1, borderColor: '#E5E7EB', padding: 12, margin: 14, marginTop: 0, flexDirection: 'row', alignItems: 'center', gap: 10 },
  paymentIcon: { fontSize: 20 },
  paymentLabel: { fontSize: 10, color: '#9CA3AF', fontWeight: '700', textTransform: 'uppercase' as const, letterSpacing: 0.5 },
  paymentValue: { fontSize: 14, color: '#0D1B2A', fontWeight: '500' },
  paymentArrow: { fontSize: 20, color: '#9CA3AF' },
  paymentOption: { backgroundColor: '#F7F8FA', borderRadius: 12, borderWidth: 1, borderColor: '#E5E7EB', padding: 12, flexDirection: 'row', alignItems: 'center', gap: 10 },
  paymentOptionActive: { borderColor: '#0E9F8E', backgroundColor: '#F0FDF4' },
  paymentOptionText: { fontSize: 14, color: '#0D1B2A', fontWeight: '600' },
  paymentOptionSub: { fontSize: 12, color: '#9CA3AF', marginTop: 2 },
  paymentCheck: { color: '#0B7A6D', fontSize: 16, fontWeight: '700' },
  clienteRilevatoBadge: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#EBF3FF', paddingHorizontal: 16, paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: '#BFDBFE' },
  clienteRilevatoBadgeText: { fontSize: 13, color: '#1E40AF', fontWeight: '500' },
  clienteRilevatoBadgeRemove: { fontSize: 16, color: '#9CA3AF', padding: 4 },
  clienteModalOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(13,27,42,0.5)', justifyContent: 'flex-end' },
  clienteModalBox: { backgroundColor: '#fff', borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 24, gap: 12, shadowColor: '#0D1B2A', shadowOffset: { width: 0, height: -2 }, shadowOpacity: 0.12, shadowRadius: 12, elevation: 6 },
  clienteModalTitolo: { fontSize: 16, fontWeight: '700', color: '#0D1B2A' },
  clienteModalSub: { fontSize: 13, color: '#6B7280', marginTop: -4 },
  clienteModalOption: { backgroundColor: '#F7F8FA', borderRadius: 12, padding: 14, borderWidth: 1, borderColor: '#E5E7EB' },
  clienteModalOptionNome: { fontSize: 14, fontWeight: '600', color: '#0D1B2A' },
  clienteModalOptionInfo: { fontSize: 12, color: '#9CA3AF', marginTop: 2 },
  clienteModalBtn: { backgroundColor: '#0D1B2A', borderRadius: 12, padding: 14, alignItems: 'center' as const, shadowColor: '#0D1B2A', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.15, shadowRadius: 5, elevation: 2 },
  clienteModalBtnText: { color: '#fff', fontSize: 14, fontWeight: '600' as const },
  clienteModalSkip: { alignItems: 'center' as const, padding: 8 },
  clienteModalSkipText: { fontSize: 13, color: '#9CA3AF' },
  clienteModalInput: { backgroundColor: '#F7F8FA', borderRadius: 12, borderWidth: 1.5, borderColor: '#E5E7EB', padding: 12, fontSize: 14, color: '#0D1B2A' },
})
