import { Dimensions, StyleSheet } from 'react-native'

const TEMPLATE_WIDTH_PX = 800
const PAGE_HEIGHT_LAYOUT = 1123

export const PREVIEW_WIDTH = Dimensions.get('window').width - 24 * 2 - 14 * 2 - 2
export const PREVIEW_HEIGHT = Math.round(PAGE_HEIGHT_LAYOUT * (PREVIEW_WIDTH / TEMPLATE_WIDTH_PX))

export const onboardingStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#0D1B2A' },
  welcomeContent: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 32, gap: 16 },
  welcomeEmoji: { fontSize: 64 },
  welcomeTitle: { fontSize: 34, fontWeight: '700', color: '#fff', textAlign: 'center', lineHeight: 42 },
  welcomeSub: { fontSize: 16, color: '#9EC5C0', textAlign: 'center', lineHeight: 24 },
  welcomeFeatures: { width: '100%', gap: 12, marginTop: 8 },
  welcomeFeature: { flexDirection: 'row', alignItems: 'center', gap: 14, backgroundColor: 'rgba(255,255,255,0.06)', borderRadius: 14, padding: 14 },
  welcomeFeatureText: { fontSize: 15, color: '#fff', fontWeight: '500' },
  stepHeader: { paddingTop: 60, paddingHorizontal: 24, paddingBottom: 16, backgroundColor: '#0D1B2A' },
  stepperRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center' },
  stepperCircle: { width: 32, height: 32, borderRadius: 16, borderWidth: 1.5, borderColor: 'rgba(255,255,255,0.25)', justifyContent: 'center', alignItems: 'center', backgroundColor: 'transparent' },
  stepperCircleActive: { borderColor: '#0E9F8E', backgroundColor: '#0E9F8E' },
  stepperCircleDone: { borderColor: '#0E9F8E', backgroundColor: 'rgba(14,159,142,0.15)' },
  stepperCircleText: { fontSize: 13, color: 'rgba(255,255,255,0.4)', fontWeight: '600' },
  stepperCircleTextActive: { color: '#fff' },
  stepperLine: { width: 24, height: 1.5, backgroundColor: 'rgba(255,255,255,0.2)' },
  stepperLineDone: { backgroundColor: '#0E9F8E' },
  stepContent: { padding: 24, gap: 12, backgroundColor: '#F7F8FA', flexGrow: 1 },
  stepTitle: { fontSize: 26, fontWeight: '700', color: '#0D1B2A', marginTop: 8 },
  stepSub: { fontSize: 14, color: '#6B7280', marginBottom: 8 },
  fieldLabel: { fontSize: 11, fontWeight: '600', color: '#9CA3AF', letterSpacing: 0.8, marginTop: 4 },
  fieldInput: { backgroundColor: '#fff', borderRadius: 12, borderWidth: 1.5, borderColor: '#E5E7EB', padding: 12, fontSize: 14, color: '#0D1B2A' },
  categorie: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 4 },
  categoriaChip: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 20, borderWidth: 1.5, borderColor: '#E5E7EB', backgroundColor: '#fff' },
  categoriaChipActive: { backgroundColor: '#0D1B2A', borderColor: '#0D1B2A' },
  categoriaText: { fontSize: 13, color: '#6B7280' },
  categoriaTextActive: { color: '#fff', fontWeight: '500' },
  nextBtn: { backgroundColor: '#0E9F8E', borderRadius: 16, padding: 16, alignItems: 'center' as const, marginTop: 16, shadowColor: '#0E9F8E', shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.25, shadowRadius: 7, elevation: 3 },
  nextBtnDisabled: { opacity: 0.4 },
  nextBtnText: { color: '#fff', fontSize: 16, fontWeight: '600' },
  modalitaTabs: { flexDirection: 'row', backgroundColor: '#fff', borderRadius: 12, padding: 3, borderWidth: 1, borderColor: '#E5E7EB', marginTop: 4 },
  modalitaTab: { flex: 1, flexDirection: 'row', justifyContent: 'center', gap: 4, paddingVertical: 7, paddingHorizontal: 4, borderRadius: 10, alignItems: 'center' as const },
  modalitaTabActive: { backgroundColor: '#0D1B2A' },
  modalitaTabText: { fontSize: 10, color: '#9CA3AF', fontWeight: '500' },
  modalitaTabTextActive: { color: '#fff' },
  testoServiziBox: { gap: 10 },
  testoServiziHint: { fontSize: 13, color: '#6B7280', lineHeight: 18 },
  testoServiziInput: { backgroundColor: '#fff', borderRadius: 12, borderWidth: 1.5, borderColor: '#E5E7EB', padding: 12, fontSize: 13, color: '#0D1B2A', minHeight: 160, textAlignVertical: 'top' },
  elaboraBtn: { backgroundColor: '#0D1B2A', borderRadius: 12, padding: 14, alignItems: 'center' as const },
  elaboraBtnText: { color: '#fff', fontSize: 14, fontWeight: '600' },
  manualBox: { gap: 10 },
  servizioItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#fff', borderRadius: 10, padding: 12, borderWidth: 1, borderColor: '#E5E7EB', shadowColor: '#0D1B2A', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.03, shadowRadius: 3, elevation: 1 },
  servizioItemLeft: { flex: 1 },
  servizioItemNome: { fontSize: 14, fontWeight: '500', color: '#0D1B2A' },
  servizioItemCosto: { fontSize: 12, color: '#0B7A6D', marginTop: 2 },
  servizioItemDel: { fontSize: 16, color: '#9CA3AF', padding: 4 },
  nuovoServizioForm: { gap: 8, backgroundColor: '#fff', borderRadius: 12, padding: 12, borderWidth: 1, borderColor: '#E5E7EB' },
  costoUnitaRow: { flexDirection: 'row', gap: 8, alignItems: 'flex-start' },
  unitaMiniChips: { flexDirection: 'row', flexWrap: 'wrap', gap: 4, flex: 1 },
  unitaMiniChip: { paddingHorizontal: 8, paddingVertical: 5, borderRadius: 10, borderWidth: 1, borderColor: '#E5E7EB', backgroundColor: '#F7F8FA' },
  unitaMiniChipActive: { backgroundColor: '#0D1B2A', borderColor: '#0D1B2A' },
  unitaMiniText: { fontSize: 10, color: '#6B7280' },
  unitaMiniTextActive: { color: '#fff' },
  aggiungiBtn: { backgroundColor: '#F0FDF4', borderRadius: 10, padding: 10, alignItems: 'center' as const, borderWidth: 1, borderColor: '#0E9F8E' },
  aggiungiBtnText: { color: '#0B7A6D', fontSize: 13, fontWeight: '600' },
  skipRow: { gap: 8 },
  skipNote: { fontSize: 12, color: '#9CA3AF', textAlign: 'center' as const },
  templateChip: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 14, paddingVertical: 10, borderRadius: 20, borderWidth: 1.5, borderColor: '#E5E7EB', backgroundColor: '#fff' },
  templateChipActive: { backgroundColor: '#0D1B2A', borderColor: '#0D1B2A' },
  templateChipEmoji: { fontSize: 16 },
  templateChipText: { fontSize: 13, color: '#6B7280', fontWeight: '500' },
  templateChipTextActive: { color: '#fff' },
  previewCard: { backgroundColor: '#fff', borderRadius: 16, padding: 14, borderWidth: 1, borderColor: '#E5E7EB', shadowColor: '#0D1B2A', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.04, shadowRadius: 4, elevation: 1 },
  previewContainer: { borderRadius: 10, overflow: 'hidden', borderWidth: 1, borderColor: '#E5E7EB', backgroundColor: '#fff' },
  label: { fontSize: 11, fontWeight: '700', letterSpacing: 0.5 },
  input: { borderRadius: 12, borderWidth: 1, padding: 12, fontSize: 14 },
  chipsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 12, paddingVertical: 9, borderRadius: 999, borderWidth: 1 },
  chipText: { fontSize: 13, color: '#6B7280' },
  chipTextActive: { color: '#fff' },
  skipBtn: { borderRadius: 16, padding: 16, alignItems: 'center' as const, borderWidth: 1.5, borderColor: '#0D1B2A', marginTop: 8 },
  skipBtnText: { color: '#0D1B2A', fontSize: 16, fontWeight: '600' },
})
