import { StyleSheet } from 'react-native'

export const storicoStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F7F8FA' },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#F7F8FA' },
  header: { backgroundColor: '#0D1B2A', paddingTop: 56, paddingBottom: 16, paddingHorizontal: 16, alignItems: 'center', justifyContent: 'center' },
  headerTitle: { color: '#fff', fontSize: 16, fontWeight: '600' },
  scroll: { flex: 1 },
  empty: { alignItems: 'center', paddingTop: 80 },
  emptyText: { fontSize: 15, color: '#9CA3AF', marginBottom: 16 },
  emptyBtn: { backgroundColor: '#0D1B2A', borderRadius: 12, paddingHorizontal: 20, paddingVertical: 12 },
  emptyBtnText: { color: '#fff', fontSize: 14, fontWeight: '600' },
  card: { backgroundColor: '#fff', borderRadius: 16, borderWidth: 1, borderColor: '#E5E7EB' },
  cardSelected: { borderColor: '#0E9F8E', backgroundColor: '#F0FDF4' },
  cardRow: { flexDirection: 'row', alignItems: 'center', padding: 14, gap: 12 },
  cardIcon: { width: 38, height: 38, backgroundColor: '#F0FDF4', borderRadius: 10, justifyContent: 'center', alignItems: 'center' },
  cardIconText: { fontSize: 18 },
  cardBody: { flex: 1 },
  cardCliente: { fontSize: 14, fontWeight: '500', color: '#0D1B2A' },
  cardData: { fontSize: 12, color: '#9CA3AF', marginTop: 2 },
  cardRight: { alignItems: 'flex-end' as const },
  cardImporto: { fontSize: 14, fontWeight: '600', color: '#0D1B2A' },
  cardActions: { flexDirection: 'row', alignItems: 'center' },
  cardActionBtn: { paddingHorizontal: 8, paddingVertical: 10 },
  cardActionIcon: { fontSize: 18 },
  detail: { borderTopWidth: 1, borderTopColor: '#F3F4F6', padding: 14, gap: 8 },
  detailText: { fontSize: 12, lineHeight: 20, color: '#6B7280', marginBottom: 4, fontFamily: 'monospace' },
  statoDropdown: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#F7F8FA', borderRadius: 10, padding: 12, borderWidth: 1, borderColor: '#E5E7EB' },
  statoDropdownText: { fontSize: 13, color: '#6B7280' },
  statoDropdownVal: { fontWeight: '600', color: '#0D1B2A' },
  statoDropdownArrow: { fontSize: 11, color: '#9CA3AF' },
  cronologiaBtn: { paddingVertical: 8, alignItems: 'center' as const },
  cronologiaBtnText: { fontSize: 13, color: '#0E9F8E', fontWeight: '500' },
  cronologiaItem: { flexDirection: 'row', justifyContent: 'space-between', backgroundColor: '#F7F8FA', borderRadius: 8, padding: 10 },
  cronologiaVer: { fontSize: 13, fontWeight: '700', color: '#9CA3AF' },
  cronologiaData: { fontSize: 12, color: '#9CA3AF' },
  cronologiaImporto: { fontSize: 12, color: '#9CA3AF' },
  editBtn: { backgroundColor: '#0D1B2A', borderRadius: 10, padding: 10, alignItems: 'center' as const },
  editBtnText: { color: '#fff', fontSize: 13, fontWeight: '600' as const },
  deleteBtn: { alignSelf: 'flex-start' as const },
  deleteBtnText: { fontSize: 13, color: '#EF4444' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'center', alignItems: 'center', padding: 32 },
  modalBox: { backgroundColor: '#fff', borderRadius: 20, padding: 20, width: '100%' },
  modalTitle: { fontSize: 16, fontWeight: '600', color: '#0D1B2A', marginBottom: 16, textAlign: 'center' as const },
  modalOption: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: '#F3F4F6' },
  modalOptionIcon: { fontSize: 20 },
  modalOptionText: { fontSize: 15, color: '#0D1B2A', fontWeight: '500' as const, textTransform: 'capitalize' as const },
  modalCancel: { paddingTop: 14, alignItems: 'center' as const },
  modalCancelText: { fontSize: 14, color: '#9CA3AF' },
  cronologiaDetail: { backgroundColor: '#F7F8FA', borderRadius: 10, padding: 12, marginTop: 4, gap: 10 },
  prevTesto: { fontSize: 12, lineHeight: 20, color: '#6B7280', fontFamily: 'monospace' },
  cardRowContainer: { flexDirection: 'row', alignItems: 'center' },
  cardMenuBtn: { paddingHorizontal: 10, paddingVertical: 10 },
  cardMenuBtnText: { fontSize: 22, color: '#9CA3AF' },
  cardTitolo: { fontSize: 11, color: '#0E9F8E', marginTop: 1 },
  selectionBar: { backgroundColor: '#0D1B2A', paddingHorizontal: 16, paddingVertical: 12, gap: 10 },
  selectionTopRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  selectionCancel: { padding: 4 },
  selectionCancelText: { color: '#9CA3AF', fontSize: 18 },
  selectionCount: { flex: 1, color: '#fff', fontSize: 14, fontWeight: '600' },
  selectionActions: { flexDirection: 'row', gap: 8 },
  selectionAction: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 6, paddingVertical: 10, borderRadius: 8, backgroundColor: 'rgba(255,255,255,0.1)' },
  selectionActionDelete: { backgroundColor: 'rgba(239,68,68,0.15)' },
  selectionActionText: { color: '#fff', fontSize: 12, fontWeight: '500', textAlign: 'center' },
  selectionActionDeleteText: { color: '#EF4444' },
})
